def pentagonalNumber(number) :
    result = int(number * (3 * number - 1)/2)
    return result
def upadtePentagonalList(limit,pentagonalList) :
    for loopVar in range(len(pentagonalList) + 1,limit) :
        pentagonalList.append(pentagonalNumber(loopVar))
    return pentagonalList
start = 1
pentagonalList = []
resultList = []
winner = 0
loopCount = 0
error = 0
pairChecked = []
limit = 10
while True :
    pentagonalList = upadtePentagonalList(limit,pentagonalList)
    try :
        for loopVar in pentagonalList :
            for loopVar2 in pentagonalList :
                loopCount += 1
                resultSet = []
                resultSet.append(loopVar)
                resultSet.append(loopVar2)
                resultSet.sort()
                if resultSet not in pairChecked :
                    if loopVar != loopVar2 :
                        pairChecked.append(resultSet)
                        numSum = loopVar + loopVar2
                        if numSum not in pentagonalList :
                            continue
                        numDiff = abs(loopVar - loopVar2)
                        print ("sum",loopVar,loopVar2,numSum)
                        print ("diff",loopVar,loopVar2,numDiff)
                        print ("loopCount=",loopCount)
                        if numDiff not in pentagonalList :
                            continue
                        resultSet.append(numDiff)
                        resultList.append(resultSet)
                        #resultList[start] = resultSet
    finally :
        error += 1
    if resultList == [] :
        limit += 5
print ("loopCount=",loopCount)
print ("Error=",error)
print (pentagonalList)
print (resultList)


# check for a number which matches this condition to check whether current algorithm is correct
# not Completed

"""


Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

"""